### ISSUE TITLE
__init__ file missing. How to use as module?

### ISSUE THREAD

**Issue by Anny-tech** [Lonitch/qeAPI#1]
Hi, I was trying to use part of the qe2cif.py code for my work using qe. However, I realized the init file is missing from the package. So, I can not really call it. Any suggestions on how to resolve this?

**Comment by Lonitch** [comment]
Hi there, the scripts are not part of package yet, and I basically use them as a tank of useful functions. If you want to use them in Jupyter notebook and `qe2cif.py` is not in your current working dir, please add the following in your notebook: 

`import sys`
`sys.path.insert(1, '/Path/to/the/scripts') #use double backslash in Windows OS`

which tells python where the scripts can be found. You can refer to `qe2DDEC_test.ipynb` for more details. Thanks.
